import { Sora } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Sidebar from "@/components/Sidebar";

const sora = Sora({ subsets: ["latin"] });

export const metadata = {
  title: "Moviedb",
  description: "Generated by Imran",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body className="dark:bg-body bg-white font-[Sora] dark:text-white text-dark">
        <Header />
        <div className="container grid lg:grid-cols-[218px_1fr] gap-[3.5rem]">
          <Sidebar />
          <div className="content">{children}</div>
        </div>
        <Footer />
        <div id="modal-root-content">
          
        </div>
      </body>
    </html>
  );
}
